import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Menu from "@/components/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen bg-white/98 overflow-hidden relative">
      <div className="relative z-10 min-h-screen">
        <Menu/>
        {children}
      </div>
    </div>
  );
}
