export const municipios = [
  // Distrito Capital
  { id: 'dc-1', nombre: 'Libertador', provinciaId: 'dc' },
  
  // Amazonas
  { id: 'amz-1', nombre: 'Alto Orinoco', provinciaId: 'amz' },
  { id: 'amz-2', nombre: 'Atabapo', provinciaId: 'amz' },
  { id: 'amz-3', nombre: 'Atures', provinciaId: 'amz' },
  { id: 'amz-4', nombre: 'Autana', provinciaId: 'amz' },
  { id: 'amz-5', nombre: 'Manapiare', provinciaId: 'amz' },
  { id: 'amz-6', nombre: 'Maroa', provinciaId: 'amz' },
  { id: 'amz-7', nombre: 'Río Negro', provinciaId: 'amz' },
  
  // Anzoátegui
  { id: 'anz-1', nombre: 'Anaco', provinciaId: 'anz' },
  { id: 'anz-2', nombre: 'Aragua', provinciaId: 'anz' },
  { id: 'anz-3', nombre: 'Bolívar', provinciaId: 'anz' },
  { id: 'anz-4', nombre: 'Bruzual', provinciaId: 'anz' },
  { id: 'anz-5', nombre: 'Carvajal', provinciaId: 'anz' },
  { id: 'anz-6', nombre: 'Cajigal', provinciaId: 'anz' },
  { id: 'anz-7', nombre: 'Freites', provinciaId: 'anz' },
  { id: 'anz-8', nombre: 'Guanipa', provinciaId: 'anz' },
  { id: 'anz-9', nombre: 'Guanta', provinciaId: 'anz' },
  { id: 'anz-10', nombre: 'Independencia', provinciaId: 'anz' },
  { id: 'anz-11', nombre: 'Libertad', provinciaId: 'anz' },
  { id: 'anz-12', nombre: 'McGregor', provinciaId: 'anz' },
  { id: 'anz-13', nombre: 'Miranda', provinciaId: 'anz' },
  { id: 'anz-14', nombre: 'Monagas', provinciaId: 'anz' },
  { id: 'anz-15', nombre: 'Peñalver', provinciaId: 'anz' },
  { id: 'anz-16', nombre: 'Píritu', provinciaId: 'anz' },
  { id: 'anz-17', nombre: 'San Juan de Capistrano', provinciaId: 'anz' },
  { id: 'anz-18', nombre: 'Santa Ana', provinciaId: 'anz' },
  { id: 'anz-19', nombre: 'Simón Rodríguez', provinciaId: 'anz' },
  { id: 'anz-20', nombre: 'Sotillo', provinciaId: 'anz' },
  { id: 'anz-21', nombre: 'Zaraza', provinciaId: 'anz' },
  
  // Apure
  { id: 'apr-1', nombre: 'Achaguas', provinciaId: 'apr' },
  { id: 'apr-2', nombre: 'Biruaca', provinciaId: 'apr' },
  { id: 'apr-3', nombre: 'Muñoz', provinciaId: 'apr' },
  { id: 'apr-4', nombre: 'Páez', provinciaId: 'apr' },
  { id: 'apr-5', nombre: 'Pedro Camejo', provinciaId: 'apr' },
  { id: 'apr-6', nombre: 'Rómulo Gallegos', provinciaId: 'apr' },
  { id: 'apr-7', nombre: 'San Fernando', provinciaId: 'apr' },
  
  // Aragua
  { id: 'ara-1', nombre: 'Bolívar', provinciaId: 'ara' },
  { id: 'ara-2', nombre: 'Camatagua', provinciaId: 'ara' },
  { id: 'ara-3', nombre: 'Francisco Linares Alcántara', provinciaId: 'ara' },
  { id: 'ara-4', nombre: 'Girardot', provinciaId: 'ara' },
  { id: 'ara-5', nombre: 'José Ángel Lamas', provinciaId: 'ara' },
  { id: 'ara-6', nombre: 'José Félix Ribas', provinciaId: 'ara' },
  { id: 'ara-7', nombre: 'José Rafael Revenga', provinciaId: 'ara' },
  { id: 'ara-8', nombre: 'Libertador', provinciaId: 'ara' },
  { id: 'ara-9', nombre: 'Mario Briceño Iragorry', provinciaId: 'ara' },
  { id: 'ara-10', nombre: 'Ocumare de la Costa de Oro', provinciaId: 'ara' },
  { id: 'ara-11', nombre: 'San Casimiro', provinciaId: 'ara' },
  { id: 'ara-12', nombre: 'San Sebastián', provinciaId: 'ara' },
  { id: 'ara-13', nombre: 'Santiago Mariño', provinciaId: 'ara' },
  { id: 'ara-14', nombre: 'Santos Michelena', provinciaId: 'ara' },
  { id: 'ara-15', nombre: 'Sucre', provinciaId: 'ara' },
  { id: 'ara-16', nombre: 'Tovar', provinciaId: 'ara' },
  { id: 'ara-17', nombre: 'Urdaneta', provinciaId: 'ara' },
  { id: 'ara-18', nombre: 'Zamora', provinciaId: 'ara' },
  
  // Barinas
  { id: 'bar-1', nombre: 'Alberto Arvelo Torrealba', provinciaId: 'bar' },
  { id: 'bar-2', nombre: 'Andrés Eloy Blanco', provinciaId: 'bar' },
  { id: 'bar-3', nombre: 'Antonio José de Sucre', provinciaId: 'bar' },
  { id: 'bar-4', nombre: 'Arismendi', provinciaId: 'bar' },
  { id: 'bar-5', nombre: 'Barinas', provinciaId: 'bar' },
  { id: 'bar-6', nombre: 'Bolívar', provinciaId: 'bar' },
  { id: 'bar-7', nombre: 'Cruz Paredes', provinciaId: 'bar' },
  { id: 'bar-8', nombre: 'Ezequiel Zamora', provinciaId: 'bar' },
  { id: 'bar-9', nombre: 'Obispos', provinciaId: 'bar' },
  { id: 'bar-10', nombre: 'Pedraza', provinciaId: 'bar' },
  { id: 'bar-11', nombre: 'Rojas', provinciaId: 'bar' },
  { id: 'bar-12', nombre: 'Sosa', provinciaId: 'bar' },
  
  // Bolívar
  { id: 'bol-1', nombre: 'Caroní', provinciaId: 'bol' },
  { id: 'bol-2', nombre: 'Cedeño', provinciaId: 'bol' },
  { id: 'bol-3', nombre: 'El Callao', provinciaId: 'bol' },
  { id: 'bol-4', nombre: 'Gran Sabana', provinciaId: 'bol' },
  { id: 'bol-5', nombre: 'Heres', provinciaId: 'bol' },
  { id: 'bol-6', nombre: 'Piar', provinciaId: 'bol' },
  { id: 'bol-7', nombre: 'Raúl Leoni', provinciaId: 'bol' },
  { id: 'bol-8', nombre: 'Roscio', provinciaId: 'bol' },
  { id: 'bol-9', nombre: 'Sifontes', provinciaId: 'bol' },
  { id: 'bol-10', nombre: 'Sucre', provinciaId: 'bol' },
  { id: 'bol-11', nombre: 'Padre Pedro Chien', provinciaId: 'bol' },
  
  // Carabobo
  { id: 'car-1', nombre: 'Bejuma', provinciaId: 'car' },
  { id: 'car-2', nombre: 'Carlos Arvelo', provinciaId: 'car' },
  { id: 'car-3', nombre: 'Diego Ibarra', provinciaId: 'car' },
  { id: 'car-4', nombre: 'Guacara', provinciaId: 'car' },
  { id: 'car-5', nombre: 'Juan José Mora', provinciaId: 'car' },
  { id: 'car-6', nombre: 'Libertador', provinciaId: 'car' },
  { id: 'car-7', nombre: 'Los Guayos', provinciaId: 'car' },
  { id: 'car-8', nombre: 'Miranda', provinciaId: 'car' },
  { id: 'car-9', nombre: 'Montalbán', provinciaId: 'car' },
  { id: 'car-10', nombre: 'Naguanagua', provinciaId: 'car' },
  { id: 'car-11', nombre: 'Puerto Cabello', provinciaId: 'car' },
  { id: 'car-12', nombre: 'San Diego', provinciaId: 'car' },
  { id: 'car-13', nombre: 'San Joaquín', provinciaId: 'car' },
  { id: 'car-14', nombre: 'Valencia', provinciaId: 'car' },
  
  // Cojedes
  { id: 'coj-1', nombre: 'Anzoátegui', provinciaId: 'coj' },
  { id: 'coj-2', nombre: 'Pao de San Juan Bautista', provinciaId: 'coj' },
  { id: 'coj-3', nombre: 'Tinaquillo', provinciaId: 'coj' },
  { id: 'coj-4', nombre: 'Girardot', provinciaId: 'coj' },
  { id: 'coj-5', nombre: 'Lima Blanco', provinciaId: 'coj' },
  { id: 'coj-6', nombre: 'Pérez de Freites', provinciaId: 'coj' },
  { id: 'coj-7', nombre: 'Ricaurte', provinciaId: 'coj' },
  { id: 'coj-8', nombre: 'Rómulo Gallegos', provinciaId: 'coj' },
  { id: 'coj-9', nombre: 'San Carlos', provinciaId: 'coj' },
  { id: 'coj-10', nombre: 'Tinaco', provinciaId: 'coj' },
  
  // Delta Amacuro
  { id: 'dfa-1', nombre: 'Antonio Díaz', provinciaId: 'dfa' },
  { id: 'dfa-2', nombre: 'Casacoima', provinciaId: 'dfa' },
  { id: 'dfa-3', nombre: 'Pedernales', provinciaId: 'dfa' },
  { id: 'dfa-4', nombre: 'Tucupita', provinciaId: 'dfa' },
  
  // Falcón
  { id: 'fal-1', nombre: 'Acosta', provinciaId: 'fal' },
  { id: 'fal-2', nombre: 'Bolívar', provinciaId: 'fal' },
  { id: 'fal-3', nombre: 'Buchivacoa', provinciaId: 'fal' },
  { id: 'fal-4', nombre: 'Cacique Manaure', provinciaId: 'fal' },
  { id: 'fal-5', nombre: 'Carirubana', provinciaId: 'fal' },
  { id: 'fal-6', nombre: 'Colina', provinciaId: 'fal' },
  { id: 'fal-7', nombre: 'Dabajuro', provinciaId: 'fal' },
  { id: 'fal-8', nombre: 'Democracia', provinciaId: 'fal' },
  { id: 'fal-9', nombre: 'Falcón', provinciaId: 'fal' },
  { id: 'fal-10', nombre: 'Federación', provinciaId: 'fal' },
  { id: 'fal-11', nombre: 'Jacura', provinciaId: 'fal' },
  { id: 'fal-12', nombre: 'Los Taques', provinciaId: 'fal' },
  { id: 'fal-13', nombre: 'Mauroa', provinciaId: 'fal' },
  { id: 'fal-14', nombre: 'Miranda', provinciaId: 'fal' },
  { id: 'fal-15', nombre: 'Monseñor Iturriza', provinciaId: 'fal' },
  { id: 'fal-16', nombre: 'Palmasola', provinciaId: 'fal' },
  { id: 'fal-17', nombre: 'Petit', provinciaId: 'fal' },
  { id: 'fal-18', nombre: 'Píritu', provinciaId: 'fal' },
  { id: 'fal-19', nombre: 'San Francisco', provinciaId: 'fal' },
  { id: 'fal-20', nombre: 'Silva', provinciaId: 'fal' },
  { id: 'fal-21', nombre: 'Sucre', provinciaId: 'fal' },
  { id: 'fal-22', nombre: 'Tocópero', provinciaId: 'fal' },
  { id: 'fal-23', nombre: 'Unión', provinciaId: 'fal' },
  { id: 'fal-24', nombre: 'Urumaco', provinciaId: 'fal' },
  { id: 'fal-25', nombre: 'Zamora', provinciaId: 'fal' },
  
  // Guárico
  { id: 'gua-1', nombre: 'Camaguán', provinciaId: 'gua' },
  { id: 'gua-2', nombre: 'Chaguaramas', provinciaId: 'gua' },
  { id: 'gua-3', nombre: 'El Socorro', provinciaId: 'gua' },
  { id: 'gua-4', nombre: 'Francisco de Miranda', provinciaId: 'gua' },
  { id: 'gua-5', nombre: 'José Félix Ribas', provinciaId: 'gua' },
  { id: 'gua-6', nombre: 'José Tadeo Monagas', provinciaId: 'gua' },
  { id: 'gua-7', nombre: 'Juan Germán Roscio', provinciaId: 'gua' },
  { id: 'gua-8', nombre: 'Julián Mellado', provinciaId: 'gua' },
  { id: 'gua-9', nombre: 'Las Mercedes', provinciaId: 'gua' },
  { id: 'gua-10', nombre: 'Leonardo Infante', provinciaId: 'gua' },
  { id: 'gua-11', nombre: 'Ortiz', provinciaId: 'gua' },
  { id: 'gua-12', nombre: 'Pedro Zaraza', provinciaId: 'gua' },
  { id: 'gua-13', nombre: 'San Gerónimo de Guayabal', provinciaId: 'gua' },
  { id: 'gua-14', nombre: 'San José de Guaribe', provinciaId: 'gua' },
  { id: 'gua-15', nombre: 'Santa María de Ipire', provinciaId: 'gua' },
  
  // Lara
  { id: 'lar-1', nombre: 'Andrés Eloy Blanco', provinciaId: 'lar' },
  { id: 'lar-2', nombre: 'Crespo', provinciaId: 'lar' },
  { id: 'lar-3', nombre: 'Iribarren', provinciaId: 'lar' },
  { id: 'lar-4', nombre: 'Jiménez', provinciaId: 'lar' },
  { id: 'lar-5', nombre: 'Morán', provinciaId: 'lar' },
  { id: 'lar-6', nombre: 'Palavecino', provinciaId: 'lar' },
  { id: 'lar-7', nombre: 'Simón Planas', provinciaId: 'lar' },
  { id: 'lar-8', nombre: 'Torres', provinciaId: 'lar' },
  { id: 'lar-9', nombre: 'Urdaneta', provinciaId: 'lar' },
  
  // Mérida
  { id: 'mer-1', nombre: 'Alberto Adriani', provinciaId: 'mer' },
  { id: 'mer-2', nombre: 'Andrés Bello', provinciaId: 'mer' },
  { id: 'mer-3', nombre: 'Antonio Pinto Salinas', provinciaId: 'mer' },
  { id: 'mer-4', nombre: 'Aricagua', provinciaId: 'mer' },
  { id: 'mer-5', nombre: 'Arzobispo Chacón', provinciaId: 'mer' },
  { id: 'mer-6', nombre: 'Campo Elías', provinciaId: 'mer' },
  { id: 'mer-7', nombre: 'Caracciolo Parra Olmedo', provinciaId: 'mer' },
  { id: 'mer-8', nombre: 'Cardenal Quintero', provinciaId: 'mer' },
  { id: 'mer-9', nombre: 'Guaraque', provinciaId: 'mer' },
  { id: 'mer-10', nombre: 'Julio César Salas', provinciaId: 'mer' },
  { id: 'mer-11', nombre: 'Justo Briceño', provinciaId: 'mer' },
  { id: 'mer-12', nombre: 'Libertador', provinciaId: 'mer' },
  { id: 'mer-13', nombre: 'Miranda', provinciaId: 'mer' },
  { id: 'mer-14', nombre: 'Obispo Ramos de Lora', provinciaId: 'mer' },
  { id: 'mer-15', nombre: 'Padre Noguera', provinciaId: 'mer' },
  { id: 'mer-16', nombre: 'Pueblo Llano', provinciaId: 'mer' },
  { id: 'mer-17', nombre: 'Rangel', provinciaId: 'mer' },
  { id: 'mer-18', nombre: 'Rivas Dávila', provinciaId: 'mer' },
  { id: 'mer-19', nombre: 'Santos Marquina', provinciaId: 'mer' },
  { id: 'mer-20', nombre: 'Sucre', provinciaId: 'mer' },
  { id: 'mer-21', nombre: 'Tovar', provinciaId: 'mer' },
  { id: 'mer-22', nombre: 'Tulio Febres Cordero', provinciaId: 'mer' },
  { id: 'mer-23', nombre: 'Zea', provinciaId: 'mer' },
  
  // Miranda
  { id: 'mir-1', nombre: 'Acevedo', provinciaId: 'mir' },
  { id: 'mir-2', nombre: 'Andrés Bello', provinciaId: 'mir' },
  { id: 'mir-3', nombre: 'Baruta', provinciaId: 'mir' },
  { id: 'mir-4', nombre: 'Buroz', provinciaId: 'mir' },
  { id: 'mir-5', nombre: 'Carrizal', provinciaId: 'mir' },
  { id: 'mir-6', nombre: 'Chacao', provinciaId: 'mir' },
  { id: 'mir-7', nombre: 'Cristóbal Rojas', provinciaId: 'mir' },
  { id: 'mir-8', nombre: 'El Hatillo', provinciaId: 'mir' },
  { id: 'mir-9', nombre: 'Guaicaipuro', provinciaId: 'mir' },
  { id: 'mir-10', nombre: 'Independencia', provinciaId: 'mir' },
  { id: 'mir-11', nombre: 'Lander', provinciaId: 'mir' },
  { id: 'mir-12', nombre: 'Los Salias', provinciaId: 'mir' },
  { id: 'mir-13', nombre: 'Páez', provinciaId: 'mir' },
  { id: 'mir-14', nombre: 'Paz Castillo', provinciaId: 'mir' },
  { id: 'mir-15', nombre: 'Pedro Gual', provinciaId: 'mir' },
  { id: 'mir-16', nombre: 'Plaza', provinciaId: 'mir' },
  { id: 'mir-17', nombre: 'Simón Bolívar', provinciaId: 'mir' },
  { id: 'mir-18', nombre: 'Sucre', provinciaId: 'mir' },
  { id: 'mir-19', nombre: 'Urdaneta', provinciaId: 'mir' },
  { id: 'mir-20', nombre: 'Zamora', provinciaId: 'mir' },
  
  // Monagas
  { id: 'mon-1', nombre: 'Acosta', provinciaId: 'mon' },
  { id: 'mon-2', nombre: 'Aguasay', provinciaId: 'mon' },
  { id: 'mon-3', nombre: 'Bolívar', provinciaId: 'mon' },
  { id: 'mon-4', nombre: 'Caripe', provinciaId: 'mon' },
  { id: 'mon-5', nombre: 'Cedeño', provinciaId: 'mon' },
  { id: 'mon-6', nombre: 'Ezequiel Zamora', provinciaId: 'mon' },
  { id: 'mon-7', nombre: 'Libertador', provinciaId: 'mon' },
  { id: 'mon-8', nombre: 'Maturín', provinciaId: 'mon' },
  { id: 'mon-9', nombre: 'Piar', provinciaId: 'mon' },
  { id: 'mon-10', nombre: 'Punceres', provinciaId: 'mon' },
  { id: 'mon-11', nombre: 'Santa Bárbara', provinciaId: 'mon' },
  { id: 'mon-12', nombre: 'Sotillo', provinciaId: 'mon' },
  { id: 'mon-13', nombre: 'Uracoa', provinciaId: 'mon' },
  
  // Nueva Esparta
  { id: 'nes-1', nombre: 'Antolín del Campo', provinciaId: 'nes' },
  { id: 'nes-2', nombre: 'Arismendi', provinciaId: 'nes' },
  { id: 'nes-3', nombre: 'Díaz', provinciaId: 'nes' },
  { id: 'nes-4', nombre: 'García', provinciaId: 'nes' },
  { id: 'nes-5', nombre: 'Gómez', provinciaId: 'nes' },
  { id: 'nes-6', nombre: 'Maneiro', provinciaId: 'nes' },
  { id: 'nes-7', nombre: 'Marcano', provinciaId: 'nes' },
  { id: 'nes-8', nombre: 'Mariño', provinciaId: 'nes' },
  { id: 'nes-9', nombre: 'Península de Macanao', provinciaId: 'nes' },
  { id: 'nes-10', nombre: 'Tubores', provinciaId: 'nes' },
  { id: 'nes-11', nombre: 'Villalba', provinciaId: 'nes' },
  
  // Portuguesa
  { id: 'por-1', nombre: 'Agua Blanca', provinciaId: 'por' },
  { id: 'por-2', nombre: 'Araure', provinciaId: 'por' },
  { id: 'por-3', nombre: 'Esteller', provinciaId: 'por' },
  { id: 'por-4', nombre: 'Guanare', provinciaId: 'por' },
  { id: 'por-5', nombre: 'Guanarito', provinciaId: 'por' },
  { id: 'por-6', nombre: 'Monseñor José Vicente de Unda', provinciaId: 'por' },
  { id: 'por-7', nombre: 'Ospino', provinciaId: 'por' },
  { id: 'por-8', nombre: 'Páez', provinciaId: 'por' },
  { id: 'por-9', nombre: 'Papelón', provinciaId: 'por' },
  { id: 'por-10', nombre: 'San Genaro de Boconoíto', provinciaId: 'por' },
  { id: 'por-11', nombre: 'San Rafael de Onoto', provinciaId: 'por' },
  { id: 'por-12', nombre: 'Santa Rosalía', provinciaId: 'por' },
  { id: 'por-13', nombre: 'Sucre', provinciaId: 'por' },
  { id: 'por-14', nombre: 'Turén', provinciaId: 'por' },
  
  // Sucre
  { id: 'suc-1', nombre: 'Andrés Eloy Blanco', provinciaId: 'suc' },
  { id: 'suc-2', nombre: 'Andrés Mata', provinciaId: 'suc' },
  { id: 'suc-3', nombre: 'Arismendi', provinciaId: 'suc' },
  { id: 'suc-4', nombre: 'Benítez', provinciaId: 'suc' },
  { id: 'suc-5', nombre: 'Bermúdez', provinciaId: 'suc' },
  { id: 'suc-6', nombre: 'Bolívar', provinciaId: 'suc' },
  { id: 'suc-7', nombre: 'Cajigal', provinciaId: 'suc' },
  { id: 'suc-8', nombre: 'Cruz Salmerón Acosta', provinciaId: 'suc' },
  { id: 'suc-9', nombre: 'Libertador', provinciaId: 'suc' },
  { id: 'suc-10', nombre: 'Mariño', provinciaId: 'suc' },
  { id: 'suc-11', nombre: 'Mejía', provinciaId: 'suc' },
  { id: 'suc-12', nombre: 'Montes', provinciaId: 'suc' },
  { id: 'suc-13', nombre: 'Ribero', provinciaId: 'suc' },
  { id: 'suc-14', nombre: 'Sucre', provinciaId: 'suc' },
  { id: 'suc-15', nombre: 'Valdéz', provinciaId: 'suc' },
  
  // Táchira
  { id: 'tac-1', nombre: 'Andrés Bello', provinciaId: 'tac' },
  { id: 'tac-2', nombre: 'Antonio Rómulo Costa', provinciaId: 'tac' },
  { id: 'tac-3', nombre: 'Ayacucho', provinciaId: 'tac' },
  { id: 'tac-4', nombre: 'Bolívar', provinciaId: 'tac' },
  { id: 'tac-5', nombre: 'Cárdenas', provinciaId: 'tac' },
  { id: 'tac-6', nombre: 'Córdoba', provinciaId: 'tac' },
  { id: 'tac-7', nombre: 'Fernández Feo', provinciaId: 'tac' },
  { id: 'tac-8', nombre: 'Francisco de Miranda', provinciaId: 'tac' },
  { id: 'tac-9', nombre: 'García de Hevia', provinciaId: 'tac' },
  { id: 'tac-10', nombre: 'Guásimos', provinciaId: 'tac' },
  { id: 'tac-11', nombre: 'Independencia', provinciaId: 'tac' },
  { id: 'tac-12', nombre: 'Jáuregui', provinciaId: 'tac' },
  { id: 'tac-13', nombre: 'José María Vargas', provinciaId: 'tac' },
  { id: 'tac-14', nombre: 'Junín', provinciaId: 'tac' },
  { id: 'tac-15', nombre: 'Libertad', provinciaId: 'tac' },
  { id: 'tac-16', nombre: 'Libertador', provinciaId: 'tac' },
  { id: 'tac-17', nombre: 'Lobatera', provinciaId: 'tac' },
  { id: 'tac-18', nombre: 'Michelena', provinciaId: 'tac' },
  { id: 'tac-19', nombre: 'Panamericano', provinciaId: 'tac' },
  { id: 'tac-20', nombre: 'Pedro María Ureña', provinciaId: 'tac' },
  { id: 'tac-21', nombre: 'Rafael Urdaneta', provinciaId: 'tac' },
  { id: 'tac-22', nombre: 'Samuel Darío Maldonado', provinciaId: 'tac' },
  { id: 'tac-23', nombre: 'San Cristóbal', provinciaId: 'tac' },
  { id: 'tac-24', nombre: 'San Judas Tadeo', provinciaId: 'tac' },
  { id: 'tac-25', nombre: 'Seboruco', provinciaId: 'tac' },
  { id: 'tac-26', nombre: 'Simón Rodríguez', provinciaId: 'tac' },
  { id: 'tac-27', nombre: 'Sucre', provinciaId: 'tac' },
  { id: 'tac-28', nombre: 'Torbes', provinciaId: 'tac' },
  { id: 'tac-29', nombre: 'Uribante', provinciaId: 'tac' },
  
  // Trujillo
  { id: 'tru-1', nombre: 'Andrés Bello', provinciaId: 'tru' },
  { id: 'tru-2', nombre: 'Boconoíto', provinciaId: 'tru' },
  { id: 'tru-3', nombre: 'Bolívar', provinciaId: 'tru' },
  { id: 'tru-4', nombre: 'Candelaria', provinciaId: 'tru' },
  { id: 'tru-5', nombre: 'Carache', provinciaId: 'tru' },
  { id: 'tru-6', nombre: 'Escuque', provinciaId: 'tru' },
  { id: 'tru-7', nombre: 'Jose Felipe Márquez Cañizales', provinciaId: 'tru' },
  { id: 'tru-8', nombre: 'Juan Vicente Campo Elías', provinciaId: 'tru' },
  { id: 'tru-9', nombre: 'La Ceiba', provinciaId: 'tru' },
  { id: 'tru-10', nombre: 'Miranda', provinciaId: 'tru' },
  { id: 'tru-11', nombre: 'Monte Carmelo', provinciaId: 'tru' },
  { id: 'tru-12', nombre: 'Motatán', provinciaId: 'tru' },
  { id: 'tru-13', nombre: 'Pampán', provinciaId: 'tru' },
  { id: 'tru-14', nombre: 'Pampanito', provinciaId: 'tru' },
  { id: 'tru-15', nombre: 'Rafael Rangel', provinciaId: 'tru' },
  { id: 'tru-16', nombre: 'San Rafael de Carvajal', provinciaId: 'tru' },
  { id: 'tru-17', nombre: 'Sucre', provinciaId: 'tru' },
  { id: 'tru-18', nombre: 'Trujillo', provinciaId: 'tru' },
  { id: 'tru-19', nombre: 'Urdaneta', provinciaId: 'tru' },
  { id: 'tru-20', nombre: 'Valera', provinciaId: 'tru' },
  
  // Vargas
  { id: 'var-1', nombre: 'Vargas', provinciaId: 'var' },
  
  // Yaracuy
  { id: 'yar-1', nombre: 'Arístides Bastidas', provinciaId: 'yar' },
  { id: 'yar-2', nombre: 'Bolívar', provinciaId: 'yar' },
  { id: 'yar-3', nombre: 'Bruzual', provinciaId: 'yar' },
  { id: 'yar-4', nombre: 'Cocorote', provinciaId: 'yar' },
  { id: 'yar-5', nombre: 'Independencia', provinciaId: 'yar' },
  { id: 'yar-6', nombre: 'José Antonio Páez', provinciaId: 'yar' },
  { id: 'yar-7', nombre: 'La Trinidad', provinciaId: 'yar' },
  { id: 'yar-8', nombre: 'Manuel Monge', provinciaId: 'yar' },
  { id: 'yar-9', nombre: 'Nirgua', provinciaId: 'yar' },
  { id: 'yar-10', nombre: 'Peña', provinciaId: 'yar' },
  { id: 'yar-11', nombre: 'San Felipe', provinciaId: 'yar' },
  { id: 'yar-12', nombre: 'Sucre', provinciaId: 'yar' },
  { id: 'yar-13', nombre: 'Urachiche', provinciaId: 'yar' },
  { id: 'yar-14', nombre: 'Veroes', provinciaId: 'yar' },
  
  // Zulia
  { id: 'zul-1', nombre: 'Almirante Padilla', provinciaId: 'zul' },
  { id: 'zul-2', nombre: 'Baralt', provinciaId: 'zul' },
  { id: 'zul-3', nombre: 'Cabimas', provinciaId: 'zul' },
  { id: 'zul-4', nombre: 'Catatumbo', provinciaId: 'zul' },
  { id: 'zul-5', nombre: 'Colón', provinciaId: 'zul' },
  { id: 'zul-6', nombre: 'Francisco Javier Pulgar', provinciaId: 'zul' },
  { id: 'zul-7', nombre: 'Jesús Enrique Lossada', provinciaId: 'zul' },
  { id: 'zul-8', nombre: 'Jesús María Semprún', provinciaId: 'zul' },
  { id: 'zul-9', nombre: 'La Cañada de Urdaneta', provinciaId: 'zul' },
  { id: 'zul-10', nombre: 'Lagunillas', provinciaId: 'zul' },
  { id: 'zul-11', nombre: 'Machiques de Perijá', provinciaId: 'zul' },
  { id: 'zul-12', nombre: 'Mara', provinciaId: 'zul' },
  { id: 'zul-13', nombre: 'Maracaibo', provinciaId: 'zul' },
  { id: 'zul-14', nombre: 'Miranda', provinciaId: 'zul' },
  { id: 'zul-15', nombre: 'Guajira', provinciaId: 'zul' },
  { id: 'zul-16', nombre: 'Mara', provinciaId: 'zul' },
  { id: 'zul-17', nombre: 'Maracaibo', provinciaId: 'zul' },
  { id: 'zul-18', nombre: 'Miranda', provinciaId: 'zul' },
  { id: 'zul-19', nombre: 'Rosario de Perijá', provinciaId: 'zul' },
  { id: 'zul-20', nombre: 'San Francisco', provinciaId: 'zul' },
  { id: 'zul-21', nombre: 'Santa Rita', provinciaId: 'zul' },
  { id: 'zul-22', nombre: 'Simón Bolívar', provinciaId: 'zul' },
  { id: 'zul-23', nombre: 'Sucre', provinciaId: 'zul' },
  { id: 'zul-24', nombre: 'Valmore Rodríguez', provinciaId: 'zul' },
  { id: 'zul-25', nombre: 'Padre Chien', provinciaId: 'zul' },

  // Dependencias Federales
  { id: 'dep-1', nombre: 'Dependencias Federales', provinciaId: 'dep' },

  // Guayana Esequiba (Zona en Reclamación)
  { id: 'guy-1', nombre: 'Guayana Esequiba', provinciaId: 'guy' }
];