export const municipios = [
  // Distrito Capital
  { id: 'libertador', nombre: 'Libertador', provinciaId: 'distrito capital' },

  // Amazonas
  { id: 'alto orinoco', nombre: 'Alto Orinoco', provinciaId: 'amazonas' },
  { id: 'atabapo', nombre: 'Atabapo', provinciaId: 'amazonas' },
  { id: 'atures', nombre: 'Atures', provinciaId: 'amazonas' },
  { id: 'autana', nombre: 'Autana', provinciaId: 'amazonas' },
  { id: 'manapiare', nombre: 'Manapiare', provinciaId: 'amazonas' },
  { id: 'maroa', nombre: 'Maroa', provinciaId: 'amazonas' },
  { id: 'rio negro', nombre: 'Río Negro', provinciaId: 'amazonas' },

  // Anzoátegui
  { id: 'anaco', nombre: 'Anaco', provinciaId: 'anzoategui' },
  { id: 'aragua', nombre: 'Aragua', provinciaId: 'anzoategui' },
  { id: 'bolivar', nombre: 'Bolívar', provinciaId: 'anzoategui' },
  { id: 'bruzual', nombre: 'Bruzual', provinciaId: 'anzoategui' },
  { id: 'carvajal', nombre: 'Carvajal', provinciaId: 'anzoategui' },
  { id: 'cajigal', nombre: 'Cajigal', provinciaId: 'anzoategui' },
  { id: 'freites', nombre: 'Freites', provinciaId: 'anzoategui' },
  { id: 'guanipa', nombre: 'Guanipa', provinciaId: 'anzoategui' },
  { id: 'guanta', nombre: 'Guanta', provinciaId: 'anzoategui' },
  { id: 'independencia', nombre: 'Independencia', provinciaId: 'anzoategui' },
  { id: 'libertad', nombre: 'Libertad', provinciaId: 'anzoategui' },
  { id: 'mcgregor', nombre: 'McGregor', provinciaId: 'anzoategui' },
  { id: 'miranda', nombre: 'Miranda', provinciaId: 'anzoategui' },
  { id: 'monagas', nombre: 'Monagas', provinciaId: 'anzoategui' },
  { id: 'penalver', nombre: 'Peñalver', provinciaId: 'anzoategui' },
  { id: 'piritu', nombre: 'Píritu', provinciaId: 'anzoategui' },
  { id: 'san juan de capistrano', nombre: 'San Juan de Capistrano', provinciaId: 'anzoategui' },
  { id: 'santa ana', nombre: 'Santa Ana', provinciaId: 'anzoategui' },
  { id: 'simon rodriguez', nombre: 'Simón Rodríguez', provinciaId: 'anzoategui' },
  { id: 'sotillo', nombre: 'Sotillo', provinciaId: 'anzoategui' },
  { id: 'zaraza', nombre: 'Zaraza', provinciaId: 'anzoategui' },

  // Apure
  { id: 'achaguas', nombre: 'Achaguas', provinciaId: 'apure' },
  { id: 'biruaca', nombre: 'Biruaca', provinciaId: 'apure' },
  { id: 'munoz', nombre: 'Muñoz', provinciaId: 'apure' },
  { id: 'paez', nombre: 'Páez', provinciaId: 'apure' },
  { id: 'pedro camejo', nombre: 'Pedro Camejo', provinciaId: 'apure' },
  { id: 'romulo gallegos', nombre: 'Rómulo Gallegos', provinciaId: 'apure' },
  { id: 'san fernando', nombre: 'San Fernando', provinciaId: 'apure' },

  // Aragua
  { id: 'bolivar aragua', nombre: 'Bolívar', provinciaId: 'aragua' },
  { id: 'camatagua', nombre: 'Camatagua', provinciaId: 'aragua' },
  { id: 'francisco linares alcantara', nombre: 'Francisco Linares Alcántara', provinciaId: 'aragua' },
  { id: 'girardot', nombre: 'Girardot', provinciaId: 'aragua' },
  { id: 'jose angel lamas', nombre: 'José Ángel Lamas', provinciaId: 'aragua' },
  { id: 'jose felix ribas', nombre: 'José Félix Ribas', provinciaId: 'aragua' },
  { id: 'jose rafael revenga', nombre: 'José Rafael Revenga', provinciaId: 'aragua' },
  { id: 'libertador aragua', nombre: 'Libertador', provinciaId: 'aragua' },
  { id: 'mario briceno iragorry', nombre: 'Mario Briceño Iragorry', provinciaId: 'aragua' },
  { id: 'ocumare de la costa de oro', nombre: 'Ocumare de la Costa de Oro', provinciaId: 'aragua' },
  { id: 'san casimiro', nombre: 'San Casimiro', provinciaId: 'aragua' },
  { id: 'san sebastian', nombre: 'San Sebastián', provinciaId: 'aragua' },
  { id: 'santiago marino', nombre: 'Santiago Mariño', provinciaId: 'aragua' },
  { id: 'santos michelena', nombre: 'Santos Michelena', provinciaId: 'aragua' },
  { id: 'sucre', nombre: 'Sucre', provinciaId: 'aragua' },
  { id: 'tovar', nombre: 'Tovar', provinciaId: 'aragua' },
  { id: 'urdaneta', nombre: 'Urdaneta', provinciaId: 'aragua' },
  { id: 'zamora', nombre: 'Zamora', provinciaId: 'aragua' },

  // Barinas
  { id: 'alberto arvelo torrealba', nombre: 'Alberto Arvelo Torrealba', provinciaId: 'barinas' },
  { id: 'andres eloy blanco', nombre: 'Andrés Eloy Blanco', provinciaId: 'barinas' },
  { id: 'antonio jose de sucre', nombre: 'Antonio José de Sucre', provinciaId: 'barinas' },
  { id: 'arismendi', nombre: 'Arismendi', provinciaId: 'barinas' },
  { id: 'barinas', nombre: 'Barinas', provinciaId: 'barinas' },
  { id: 'bolivar barinas', nombre: 'Bolívar', provinciaId: 'barinas' },
  { id: 'cruz paredes', nombre: 'Cruz Paredes', provinciaId: 'barinas' },
  { id: 'ezequiel zamora', nombre: 'Ezequiel Zamora', provinciaId: 'barinas' },
  { id: 'obispos', nombre: 'Obispos', provinciaId: 'barinas' },
  { id: 'pedraza', nombre: 'Pedraza', provinciaId: 'barinas' },
  { id: 'rojas', nombre: 'Rojas', provinciaId: 'barinas' },
  { id: 'sosa', nombre: 'Sosa', provinciaId: 'barinas' },

  // Bolívar
  { id: 'caroni', nombre: 'Caroní', provinciaId: 'bolivar' },
  { id: 'cedeno', nombre: 'Cedeño', provinciaId: 'bolivar' },
  { id: 'el callao', nombre: 'El Callao', provinciaId: 'bolivar' },
  { id: 'gran sabana', nombre: 'Gran Sabana', provinciaId: 'bolivar' },
  { id: 'heres', nombre: 'Heres', provinciaId: 'bolivar' },
  { id: 'piar', nombre: 'Piar', provinciaId: 'bolivar' },
  { id: 'raul leoni', nombre: 'Raúl Leoni', provinciaId: 'bolivar' },
  { id: 'roscio', nombre: 'Roscio', provinciaId: 'bolivar' },
  { id: 'sifontes', nombre: 'Sifontes', provinciaId: 'bolivar' },
  { id: 'sucre bolivar', nombre: 'Sucre', provinciaId: 'bolivar' },
  { id: 'padre pedro chien', nombre: 'Padre Pedro Chien', provinciaId: 'bolivar' },

  // Carabobo
  { id: 'bejuma', nombre: 'Bejuma', provinciaId: 'carabobo' },
  { id: 'carlos arvelo', nombre: 'Carlos Arvelo', provinciaId: 'carabobo' },
  { id: 'diego ibarra', nombre: 'Diego Ibarra', provinciaId: 'carabobo' },
  { id: 'guacara', nombre: 'Guacara', provinciaId: 'carabobo' },
  { id: 'juan jose mora', nombre: 'Juan José Mora', provinciaId: 'carabobo' },
  { id: 'libertador carabobo', nombre: 'Libertador', provinciaId: 'carabobo' },
  { id: 'los guayos', nombre: 'Los Guayos', provinciaId: 'carabobo' },
  { id: 'miranda carabobo', nombre: 'Miranda', provinciaId: 'carabobo' },
  { id: 'montalban', nombre: 'Montalbán', provinciaId: 'carabobo' },
  { id: 'naguanagua', nombre: 'Naguanagua', provinciaId: 'carabobo' },
  { id: 'puerto cabello', nombre: 'Puerto Cabello', provinciaId: 'carabobo' },
  { id: 'san diego', nombre: 'San Diego', provinciaId: 'carabobo' },
  { id: 'san joaquin', nombre: 'San Joaquín', provinciaId: 'carabobo' },
  { id: 'valencia', nombre: 'Valencia', provinciaId: 'carabobo' },

  // Cojedes
  { id: 'anzoategui', nombre: 'Anzoátegui', provinciaId: 'cojedes' },
  { id: 'pao de san juan bautista', nombre: 'Pao de San Juan Bautista', provinciaId: 'cojedes' },
  { id: 'tinaquillo', nombre: 'Tinaquillo', provinciaId: 'cojedes' },
  { id: 'girardot cojedes', nombre: 'Girardot', provinciaId: 'cojedes' },
  { id: 'lima blanco', nombre: 'Lima Blanco', provinciaId: 'cojedes' },
  { id: 'perez de freites', nombre: 'Pérez de Freites', provinciaId: 'cojedes' },
  { id: 'ricaurte', nombre: 'Ricaurte', provinciaId: 'cojedes' },
  { id: 'romulo gallegos cojedes', nombre: 'Rómulo Gallegos', provinciaId: 'cojedes' },
  { id: 'san carlos', nombre: 'San Carlos', provinciaId: 'cojedes' },
  { id: 'tinaco', nombre: 'Tinaco', provinciaId: 'cojedes' },

  // Delta Amacuro
  { id: 'antonio diaz', nombre: 'Antonio Díaz', provinciaId: 'delta amacuro' },
  { id: 'casacoima', nombre: 'Casacoima', provinciaId: 'delta amacuro' },
  { id: 'pedernales', nombre: 'Pedernales', provinciaId: 'delta amacuro' },
  { id: 'tucupita', nombre: 'Tucupita', provinciaId: 'delta amacuro' },

  // Falcón
  { id: 'acosta', nombre: 'Acosta', provinciaId: 'falcon' },
  { id: 'bolivar falcon', nombre: 'Bolívar', provinciaId: 'falcon' },
  { id: 'buchivacoa', nombre: 'Buchivacoa', provinciaId: 'falcon' },
  { id: 'cacique manaure', nombre: 'Cacique Manaure', provinciaId: 'falcon' },
  { id: 'carirubana', nombre: 'Carirubana', provinciaId: 'falcon' },
  { id: 'colina', nombre: 'Colina', provinciaId: 'falcon' },
  { id: 'dabajuro', nombre: 'Dabajuro', provinciaId: 'falcon' },
  { id: 'democracia', nombre: 'Democracia', provinciaId: 'falcon' },
  { id: 'falcon', nombre: 'Falcón', provinciaId: 'falcon' },
  { id: 'federacion', nombre: 'Federación', provinciaId: 'falcon' },
  { id: 'jacura', nombre: 'Jacura', provinciaId: 'falcon' },
  { id: 'los taques', nombre: 'Los Taques', provinciaId: 'falcon' },
  { id: 'mauroa', nombre: 'Mauroa', provinciaId: 'falcon' },
  { id: 'miranda falcon', nombre: 'Miranda', provinciaId: 'falcon' },
  { id: 'monsenor iturriza', nombre: 'Monseñor Iturriza', provinciaId: 'falcon' },
  { id: 'palmasola', nombre: 'Palmasola', provinciaId: 'falcon' },
  { id: 'petit', nombre: 'Petit', provinciaId: 'falcon' },
  { id: 'piritu falcon', nombre: 'Píritu', provinciaId: 'falcon' },
  { id: 'san francisco', nombre: 'San Francisco', provinciaId: 'falcon' },
  { id: 'silva', nombre: 'Silva', provinciaId: 'falcon' },
  { id: 'sucre falcon', nombre: 'Sucre', provinciaId: 'falcon' },
  { id: 'tocopero', nombre: 'Tocópero', provinciaId: 'falcon' },
  { id: 'union', nombre: 'Unión', provinciaId: 'falcon' },
  { id: 'urumaco', nombre: 'Urumaco', provinciaId: 'falcon' },
  { id: 'zamora falcon', nombre: 'Zamora', provinciaId: 'falcon' },

  // Guárico
  { id: 'camaguan', nombre: 'Camaguán', provinciaId: 'guarico' },
  { id: 'chaguaramas', nombre: 'Chaguaramas', provinciaId: 'guarico' },
  { id: 'el socorro', nombre: 'El Socorro', provinciaId: 'guarico' },
  { id: 'francisco de miranda', nombre: 'Francisco de Miranda', provinciaId: 'guarico' },
  { id: 'jose felix ribas guarico', nombre: 'José Félix Ribas', provinciaId: 'guarico' },
  { id: 'jose tadeo monagas', nombre: 'José Tadeo Monagas', provinciaId: 'guarico' },
  { id: 'juan german roscio', nombre: 'Juan Germán Roscio', provinciaId: 'guarico' },
  { id: 'julian mellado', nombre: 'Julián Mellado', provinciaId: 'guarico' },
  { id: 'las mercedes', nombre: 'Las Mercedes', provinciaId: 'guarico' },
  { id: 'leonardo infante', nombre: 'Leonardo Infante', provinciaId: 'guarico' },
  { id: 'ortiz', nombre: 'Ortiz', provinciaId: 'guarico' },
  { id: 'pedro zaraza', nombre: 'Pedro Zaraza', provinciaId: 'guarico' },
  { id: 'san geronimo de guayabal', nombre: 'San Gerónimo de Guayabal', provinciaId: 'guarico' },
  { id: 'san jose de guaribe', nombre: 'San José de Guaribe', provinciaId: 'guarico' },
  { id: 'santa maria de ipire', nombre: 'Santa María de Ipire', provinciaId: 'guarico' },

  // Lara
  { id: 'andres eloy blanco lara', nombre: 'Andrés Eloy Blanco', provinciaId: 'lara' },
  { id: 'crespo', nombre: 'Crespo', provinciaId: 'lara' },
  { id: 'iribarren', nombre: 'Iribarren', provinciaId: 'lara' },
  { id: 'jimenez', nombre: 'Jiménez', provinciaId: 'lara' },
  { id: 'moran', nombre: 'Morán', provinciaId: 'lara' },
  { id: 'palavecino', nombre: 'Palavecino', provinciaId: 'lara' },
  { id: 'simon planas', nombre: 'Simón Planas', provinciaId: 'lara' },
  { id: 'torres', nombre: 'Torres', provinciaId: 'lara' },
  { id: 'urdaneta lara', nombre: 'Urdaneta', provinciaId: 'lara' },

  // Mérida
  { id: 'alberto adriani', nombre: 'Alberto Adriani', provinciaId: 'merida' },
  { id: 'andres bello', nombre: 'Andrés Bello', provinciaId: 'merida' },
  { id: 'antonio pinto salinas', nombre: 'Antonio Pinto Salinas', provinciaId: 'merida' },
  { id: 'aricagua', nombre: 'Aricagua', provinciaId: 'merida' },
  { id: 'arzobispo chacon', nombre: 'Arzobispo Chacón', provinciaId: 'merida' },
  { id: 'campo elias', nombre: 'Campo Elías', provinciaId: 'merida' },
  { id: 'caracciolo parra olmedo', nombre: 'Caracciolo Parra Olmedo', provinciaId: 'merida' },
  { id: 'cardenal quintero', nombre: 'Cardenal Quintero', provinciaId: 'merida' },
  { id: 'guaraque', nombre: 'Guaraque', provinciaId: 'merida' },
  { id: 'julio cesar salas', nombre: 'Julio César Salas', provinciaId: 'merida' },
  { id: 'justo briceno', nombre: 'Justo Briceño', provinciaId: 'merida' },
  { id: 'libertador merida', nombre: 'Libertador', provinciaId: 'merida' },
  { id: 'miranda merida', nombre: 'Miranda', provinciaId: 'merida' },
  { id: 'obispo ramos de lora', nombre: 'Obispo Ramos de Lora', provinciaId: 'merida' },
  { id: 'padre noguera', nombre: 'Padre Noguera', provinciaId: 'merida' },
  { id: 'pueblo llano', nombre: 'Pueblo Llano', provinciaId: 'merida' },
  { id: 'rangel', nombre: 'Rangel', provinciaId: 'merida' },
  { id: 'rivas davila', nombre: 'Rivas Dávila', provinciaId: 'merida' },
  { id: 'santos marquina', nombre: 'Santos Marquina', provinciaId: 'merida' },
  { id: 'sucre merida', nombre: 'Sucre', provinciaId: 'merida' },
  { id: 'tovar merida', nombre: 'Tovar', provinciaId: 'merida' },
  { id: 'tulio febres cordero', nombre: 'Tulio Febres Cordero', provinciaId: 'merida' },
  { id: 'zea', nombre: 'Zea', provinciaId: 'merida' },

  // Miranda
  { id: 'acevedo', nombre: 'Acevedo', provinciaId: 'miranda' },
  { id: 'andres bello miranda', nombre: 'Andrés Bello', provinciaId: 'miranda' },
  { id: 'baruta', nombre: 'Baruta', provinciaId: 'miranda' },
  { id: 'buroz', nombre: 'Buroz', provinciaId: 'miranda' },
  { id: 'carrizal', nombre: 'Carrizal', provinciaId: 'miranda' },
  { id: 'chacao', nombre: 'Chacao', provinciaId: 'miranda' },
  { id: 'cristobal rojas', nombre: 'Cristóbal Rojas', provinciaId: 'miranda' },
  { id: 'el hatillo', nombre: 'El Hatillo', provinciaId: 'miranda' },
  { id: 'guaicaipuro', nombre: 'Guaicaipuro', provinciaId: 'miranda' },
  { id: 'independencia miranda', nombre: 'Independencia', provinciaId: 'miranda' },
  { id: 'lander', nombre: 'Lander', provinciaId: 'miranda' },
  { id: 'los salias', nombre: 'Los Salias', provinciaId: 'miranda' },
  { id: 'paez miranda', nombre: 'Páez', provinciaId: 'miranda' },
  { id: 'paz castillo', nombre: 'Paz Castillo', provinciaId: 'miranda' },
  { id: 'pedro gual', nombre: 'Pedro Gual', provinciaId: 'miranda' },
  { id: 'plaza', nombre: 'Plaza', provinciaId: 'miranda' },
  { id: 'simon bolivar', nombre: 'Simón Bolívar', provinciaId: 'miranda' },
  { id: 'sucre miranda', nombre: 'Sucre', provinciaId: 'miranda' },
  { id: 'urdaneta miranda', nombre: 'Urdaneta', provinciaId: 'miranda' },
  { id: 'zamora miranda', nombre: 'Zamora', provinciaId: 'miranda' },

  // Monagas
  { id: 'acosta monagas', nombre: 'Acosta', provinciaId: 'monagas' },
  { id: 'aguasay', nombre: 'Aguasay', provinciaId: 'monagas' },
  { id: 'bolivar monagas', nombre: 'Bolívar', provinciaId: 'monagas' },
  { id: 'caripe', nombre: 'Caripe', provinciaId: 'monagas' },
  { id: 'cedeno monagas', nombre: 'Cedeño', provinciaId: 'monagas' },
  { id: 'ezequiel zamora monagas', nombre: 'Ezequiel Zamora', provinciaId: 'monagas' },
  { id: 'libertador monagas', nombre: 'Libertador', provinciaId: 'monagas' },
  { id: 'maturin', nombre: 'Maturín', provinciaId: 'monagas' },
  { id: 'piar monagas', nombre: 'Piar', provinciaId: 'monagas' },
  { id: 'punceres', nombre: 'Punceres', provinciaId: 'monagas' },
  { id: 'santa barbara', nombre: 'Santa Bárbara', provinciaId: 'monagas' },
  { id: 'sotillo monagas', nombre: 'Sotillo', provinciaId: 'monagas' },
  { id: 'uracoa', nombre: 'Uracoa', provinciaId: 'monagas' },

  // Nueva Esparta
  { id: 'antolin del campo', nombre: 'Antolín del Campo', provinciaId: 'nueva esparta' },
  { id: 'arismendi nueva esparta', nombre: 'Arismendi', provinciaId: 'nueva esparta' },
  { id: 'diaz', nombre: 'Díaz', provinciaId: 'nueva esparta' },
  { id: 'garcia', nombre: 'García', provinciaId: 'nueva esparta' },
  { id: 'gomez', nombre: 'Gómez', provinciaId: 'nueva esparta' },
  { id: 'maneiro', nombre: 'Maneiro', provinciaId: 'nueva esparta' },
  { id: 'marcano', nombre: 'Marcano', provinciaId: 'nueva esparta' },
  { id: 'marino', nombre: 'Mariño', provinciaId: 'nueva esparta' },
  { id: 'peninsula de macanao', nombre: 'Península de Macanao', provinciaId: 'nueva esparta' },
  { id: 'tubores', nombre: 'Tubores', provinciaId: 'nueva esparta' },
  { id: 'villalba', nombre: 'Villalba', provinciaId: 'nueva esparta' },

  // Portuguesa
  { id: 'agua blanca', nombre: 'Agua Blanca', provinciaId: 'portuguesa' },
  { id: 'araure', nombre: 'Araure', provinciaId: 'portuguesa' },
  { id: 'esteller', nombre: 'Esteller', provinciaId: 'portuguesa' },
  { id: 'guanare', nombre: 'Guanare', provinciaId: 'portuguesa' },
  { id: 'guanarito', nombre: 'Guanarito', provinciaId: 'portuguesa' },
  { id: 'monsenor jose vicente de unda', nombre: 'Monseñor José Vicente de Unda', provinciaId: 'portuguesa' },
  { id: 'ospino', nombre: 'Ospino', provinciaId: 'portuguesa' },
  { id: 'paez portuguesa', nombre: 'Páez', provinciaId: 'portuguesa' },
  { id: 'papelon', nombre: 'Papelón', provinciaId: 'portuguesa' },
  { id: 'san genaro de boconoito', nombre: 'San Genaro de Boconoíto', provinciaId: 'portuguesa' },
  { id: 'san rafael de onoto', nombre: 'San Rafael de Onoto', provinciaId: 'portuguesa' },
  { id: 'santa rosalia', nombre: 'Santa Rosalía', provinciaId: 'portuguesa' },
  { id: 'sucre portuguesa', nombre: 'Sucre', provinciaId: 'portuguesa' },
  { id: 'turen', nombre: 'Turén', provinciaId: 'portuguesa' },

  // Sucre
  { id: 'andres eloy blanco sucre', nombre: 'Andrés Eloy Blanco', provinciaId: 'sucre' },
  { id: 'andres mata', nombre: 'Andrés Mata', provinciaId: 'sucre' },
  { id: 'arismendi sucre', nombre: 'Arismendi', provinciaId: 'sucre' },
  { id: 'benitez', nombre: 'Benítez', provinciaId: 'sucre' },
  { id: 'bermudez', nombre: 'Bermúdez', provinciaId: 'sucre' },
  { id: 'bolivar sucre', nombre: 'Bolívar', provinciaId: 'sucre' },
  { id: 'cajigal sucre', nombre: 'Cajigal', provinciaId: 'sucre' },
  { id: 'cruz salmeron acosta', nombre: 'Cruz Salmerón Acosta', provinciaId: 'sucre' },
  { id: 'libertador sucre', nombre: 'Libertador', provinciaId: 'sucre' },
  { id: 'marino sucre', nombre: 'Mariño', provinciaId: 'sucre' },
  { id: 'mejia', nombre: 'Mejía', provinciaId: 'sucre' },
  { id: 'montes', nombre: 'Montes', provinciaId: 'sucre' },
  { id: 'ribero', nombre: 'Ribero', provinciaId: 'sucre' },
  { id: 'sucre sucre', nombre: 'Sucre', provinciaId: 'sucre' },
  { id: 'valdez', nombre: 'Valdéz', provinciaId: 'sucre' },

  // Táchira
  { id: 'andres bello tachira', nombre: 'Andrés Bello', provinciaId: 'tachira' },
  { id: 'antonio romulo costa', nombre: 'Antonio Rómulo Costa', provinciaId: 'tachira' },
  { id: 'ayacucho', nombre: 'Ayacucho', provinciaId: 'tachira' },
  { id: 'bolivar tachira', nombre: 'Bolívar', provinciaId: 'tachira' },
  { id: 'cardenas', nombre: 'Cárdenas', provinciaId: 'tachira' },
  { id: 'cordoba', nombre: 'Córdoba', provinciaId: 'tachira' },
  { id: 'fernandez feo', nombre: 'Fernández Feo', provinciaId: 'tachira' },
  { id: 'francisco de miranda tachira', nombre: 'Francisco de Miranda', provinciaId: 'tachira' },
  { id: 'garcia de hevia', nombre: 'García de Hevia', provinciaId: 'tachira' },
  { id: 'guasimos', nombre: 'Guásimos', provinciaId: 'tachira' },
  { id: 'independencia tachira', nombre: 'Independencia', provinciaId: 'tachira' },
  { id: 'jauregui', nombre: 'Jáuregui', provinciaId: 'tachira' },
  { id: 'jose maria vargas', nombre: 'José María Vargas', provinciaId: 'tachira' },
  { id: 'junin', nombre: 'Junín', provinciaId: 'tachira' },
  { id: 'libertad tachira', nombre: 'Libertad', provinciaId: 'tachira' },
  { id: 'libertador tachira', nombre: 'Libertador', provinciaId: 'tachira' },
  { id: 'lobatera', nombre: 'Lobatera', provinciaId: 'tachira' },
  { id: 'michelena', nombre: 'Michelena', provinciaId: 'tachira' },
  { id: 'panamericano', nombre: 'Panamericano', provinciaId: 'tachira' },
  { id: 'pedro maria urena', nombre: 'Pedro María Ureña', provinciaId: 'tachira' },
  { id: 'rafael urdaneta', nombre: 'Rafael Urdaneta', provinciaId: 'tachira' },
  { id: 'samuel dario maldonado', nombre: 'Samuel Darío Maldonado', provinciaId: 'tachira' },
  { id: 'san cristobal', nombre: 'San Cristóbal', provinciaId: 'tachira' },
  { id: 'san judas tadeo', nombre: 'San Judas Tadeo', provinciaId: 'tachira' },
  { id: 'seboruco', nombre: 'Seboruco', provinciaId: 'tachira' },
  { id: 'simon rodriguez tachira', nombre: 'Simón Rodríguez', provinciaId: 'tachira' },
  { id: 'sucre tachira', nombre: 'Sucre', provinciaId: 'tachira' },
  { id: 'torbes', nombre: 'Torbes', provinciaId: 'tachira' },
  { id: 'uribante', nombre: 'Uribante', provinciaId: 'tachira' },

  // Trujillo
  { id: 'andres bello trujillo', nombre: 'Andrés Bello', provinciaId: 'trujillo' },
  { id: 'boconoito', nombre: 'Boconoíto', provinciaId: 'trujillo' },
  { id: 'bolivar trujillo', nombre: 'Bolívar', provinciaId: 'trujillo' },
  { id: 'candelaria', nombre: 'Candelaria', provinciaId: 'trujillo' },
  { id: 'carache', nombre: 'Carache', provinciaId: 'trujillo' },
  { id: 'escuque', nombre: 'Escuque', provinciaId: 'trujillo' },
  { id: 'jose felipe marquez canizales', nombre: 'Jose Felipe Márquez Cañizales', provinciaId: 'trujillo' },
  { id: 'juan vicente campo elias', nombre: 'Juan Vicente Campo Elías', provinciaId: 'trujillo' },
  { id: 'la ceiba', nombre: 'La Ceiba', provinciaId: 'trujillo' },
  { id: 'miranda trujillo', nombre: 'Miranda', provinciaId: 'trujillo' },
  { id: 'monte carmelo', nombre: 'Monte Carmelo', provinciaId: 'trujillo' },
  { id: 'motatan', nombre: 'Motatán', provinciaId: 'trujillo' },
  { id: 'pampan', nombre: 'Pampán', provinciaId: 'trujillo' },
  { id: 'pampanito', nombre: 'Pampanito', provinciaId: 'trujillo' },
  { id: 'rafael rangel', nombre: 'Rafael Rangel', provinciaId: 'trujillo' },
  { id: 'san rafael de carvajal', nombre: 'San Rafael de Carvajal', provinciaId: 'trujillo' },
  { id: 'sucre trujillo', nombre: 'Sucre', provinciaId: 'trujillo' },
  { id: 'trujillo', nombre: 'Trujillo', provinciaId: 'trujillo' },
  { id: 'urdaneta trujillo', nombre: 'Urdaneta', provinciaId: 'trujillo' },
  { id: 'valera', nombre: 'Valera', provinciaId: 'trujillo' },

  // Vargas
  { id: 'vargas', nombre: 'Vargas', provinciaId: 'vargas' },

  // Yaracuy
  { id: 'aristides bastidas', nombre: 'Arístides Bastidas', provinciaId: 'yaracuy' },
  { id: 'bolivar yaracuy', nombre: 'Bolívar', provinciaId: 'yaracuy' },
  { id: 'bruzual yaracuy', nombre: 'Bruzual', provinciaId: 'yaracuy' },
  { id: 'cocorote', nombre: 'Cocorote', provinciaId: 'yaracuy' },
  { id: 'independencia yaracuy', nombre: 'Independencia', provinciaId: 'yaracuy' },
  { id: 'jose antonio paez', nombre: 'José Antonio Páez', provinciaId: 'yaracuy' },
  { id: 'la trinidad', nombre: 'La Trinidad', provinciaId: 'yaracuy' },
  { id: 'manuel monge', nombre: 'Manuel Monge', provinciaId: 'yaracuy' },
  { id: 'nirgua', nombre: 'Nirgua', provinciaId: 'yaracuy' },
  { id: 'pena', nombre: 'Peña', provinciaId: 'yaracuy' },
  { id: 'san felipe', nombre: 'San Felipe', provinciaId: 'yaracuy' },
  { id: 'sucre yaracuy', nombre: 'Sucre', provinciaId: 'yaracuy' },
  { id: 'urachiche', nombre: 'Urachiche', provinciaId: 'yaracuy' },
  { id: 'veroes', nombre: 'Veroes', provinciaId: 'yaracuy' },

  // Zulia
  { id: 'almirante padilla', nombre: 'Almirante Padilla', provinciaId: 'zulia' },
  { id: 'baralt', nombre: 'Baralt', provinciaId: 'zulia' },
  { id: 'cabimas', nombre: 'Cabimas', provinciaId: 'zulia' },
  { id: 'catatumbo', nombre: 'Catatumbo', provinciaId: 'zulia' },
  { id: 'colon', nombre: 'Colón', provinciaId: 'zulia' },
  { id: 'francisco javier pulgar', nombre: 'Francisco Javier Pulgar', provinciaId: 'zulia' },
  { id: 'jesus enrique lossada', nombre: 'Jesús Enrique Lossada', provinciaId: 'zulia' },
  { id: 'jesus maria semprun', nombre: 'Jesús María Semprún', provinciaId: 'zulia' },
  { id: 'la canada de urdaneta', nombre: 'La Cañada de Urdaneta', provinciaId: 'zulia' },
  { id: 'lagunillas', nombre: 'Lagunillas', provinciaId: 'zulia' },
  { id: 'machiques de perija', nombre: 'Machiques de Perijá', provinciaId: 'zulia' },
  { id: 'mara', nombre: 'Mara', provinciaId: 'zulia' },
  { id: 'maracaibo', nombre: 'Maracaibo', provinciaId: 'zulia' },
  { id: 'miranda zulia', nombre: 'Miranda', provinciaId: 'zulia' },
  { id: 'guajira', nombre: 'Guajira', provinciaId: 'zulia' },
  { id: 'mara zulia', nombre: 'Mara', provinciaId: 'zulia' },
  { id: 'maracaibo zulia', nombre: 'Maracaibo', provinciaId: 'zulia' },
  { id: 'miranda zulia 2', nombre: 'Miranda', provinciaId: 'zulia' },
  { id: 'rosario de perija', nombre: 'Rosario de Perijá', provinciaId: 'zulia' },
  { id: 'san francisco zulia', nombre: 'San Francisco', provinciaId: 'zulia' },
  { id: 'santa rita', nombre: 'Santa Rita', provinciaId: 'zulia' },
  { id: 'simon bolivar zulia', nombre: 'Simón Bolívar', provinciaId: 'zulia' },
  { id: 'sucre zulia', nombre: 'Sucre', provinciaId: 'zulia' },
  { id: 'valmore rodriguez', nombre: 'Valmore Rodríguez', provinciaId: 'zulia' },
  { id: 'padre chien', nombre: 'Padre Chien', provinciaId: 'zulia' },

  // Dependencias Federales
  { id: 'dependencias federales', nombre: 'Dependencias Federales', provinciaId: 'dependencias federales' },

  // Guayana Esequiba
  { id: 'guayana esequiba', nombre: 'Guayana Esequiba', provinciaId: 'guayana esequiba' },
];
