const nombreRutas = {
    '/administrador': 'Panel de Control',
    '/administrador/usuarios': 'Gestión de Usuarios',    
    '/administrador/usuarios/nuevo': 'Nuevo Usuario',
    '/administrador/usuarios/editar': 'Editar Usuario',
    '/administrador/usuarios/roles': 'Asignar Roles',
    '/administrador/usuarios/activar': 'Activar/Desactivar Usuarios',
    '/administrador/usuarios/eliminar': 'Eliminar Usuarios',
    '/administrador/usuarios/clave': 'Restablecer Contraseña',
    '/administrador/hospitales': 'Gestión de Hospitales',
    '/administrador/hospitales/nuevo': 'Nuevo Hospital',
    '/administrador/hospitales/editar': 'Editar Hospital',
    '/administrador/hospitales/ficha': 'Ficha de Insumos',
    '/administrador/hospitales/activar': 'Activar/Desactivar Hospitales',
    '/administrador/insumos': 'Gestión de Insumos',
    '/administrador/insumos/nuevo': 'Nuevo Insumo',
    '/administrador/insumos/editar': 'Editar Insumo',
    '/administrador/insumos/activar': 'Activar/Desactivar Insumos',
    '/administrador/insumos/eliminar': 'Eliminar Insumos',
    '/administrador/movimientos': 'Gestión de Movimientos',
    '/administrador/movimientos/nuevo': 'Nuevo Movimiento',
    '/administrador/movimientos/archivo': 'Nuevo Movimiento por Archivo',
    '/administrador/movimientos/editar': 'Editar Movimiento',
    '/administrador/movimientos/activar': 'Activar/Desactivar Movimientos',
    '/administrador/movimientos/eliminar': 'Eliminar Movimientos',
    '/administrador/inventario': 'Gestión de Inventario',
    '/administrador/inventario/nuevo': 'Nuevo Lote',
    '/administrador/inventario/editar': 'Editar Lote',
    '/administrador/inventario/activar': 'Activar/Desactivar Lotes',
    '/administrador/inventario/eliminar': 'Eliminar Lotes',
    '/administrador/almacenes': 'Gestión de Almacenes',
    '/administrador/almacenes/nuevo': 'Nuevo Almacén',
    '/administrador/almacenes/editar': 'Editar Almacén',
    '/administrador/almacenes/activar': 'Activar/Desactivar Almacenes',
    '/administrador/almacenes/eliminar': 'Eliminar Almacenes',
    '/administrador/mapa': 'Mapa Georeferenciado',
    '/administrador/solicitudes': 'Gestión de Solicitudes',
    '/administrador/logistica': 'Gestión de Seguimiento',
    '/administrador/configuracion': 'Configuración del Sistema',
    '/administrador/perfil': 'Mi Perfil',
    '/administrador/reportes': 'Reportes del Sistema',
    '/administrador/reportes/movimientos': 'Reporte de Movimientos',
    '/administrador/reportes/inventario': 'Reporte de Inventario',
    '/administrador/reportes/pacientes': 'Reporte de Pacientes',
    '/administrador/reportes/traza': 'Reporte de Traza Insumo',
    '/administrador/reportes/general': 'Reporte General',
    '/administrador/herramientas': 'Herramientas',
    '/administrador/herramientas/comparar-insumos': 'Comparar Insumos',
    '/administrador/sedes': 'Gestión de Sedes',
    '/administrador/sedes/nuevo': 'Registrar Sede',
    '/administrador/sedes/editar': 'Editar Sede',
    '/administrador/sedes/activar': 'Activar/Desactivar Sedes',
    '/administrador/sedes/eliminar': 'Eliminar Sedes',
};

export default nombreRutas;
