export const provincias = [
    { id: 'dc', nombre: 'Distrito Capital' },
    { id: 'amz', nombre: 'Amazonas' },
    { id: 'anz', nombre: 'Anzoátegui' },
    { id: 'apr', nombre: 'Apure' },
    { id: 'ara', nombre: 'Aragua' },
    { id: 'bar', nombre: 'Barinas' },
    { id: 'bol', nombre: 'Bolívar' },
    { id: 'car', nombre: 'Carabobo' },
    { id: 'coj', nombre: 'Cojedes' },
    { id: 'dfa', nombre: 'Delta Amacuro' },
    { id: 'fal', nombre: 'Falcón' },
    { id: 'gua', nombre: 'Guárico' },
    { id: 'lar', nombre: 'Lara' },
    { id: 'mer', nombre: 'Mérida' },
    { id: 'mir', nombre: 'Miranda' },
    { id: 'mon', nombre: 'Monagas' },
    { id: 'nes', nombre: 'Nueva Esparta' },
    { id: 'por', nombre: 'Portuguesa' },
    { id: 'suc', nombre: 'Sucre' },
    { id: 'tac', nombre: 'Táchira' },
    { id: 'tru', nombre: 'Trujillo' },
    { id: 'var', nombre: 'Vargas' },
    { id: 'yar', nombre: 'Yaracuy' },
    { id: 'zul', nombre: 'Zulia' },
    { id: 'dep', nombre: 'Dependencias Federales' },
    { id: 'gua', nombre: 'Guayana Esequiba' } // Zona en Reclamación
];