export const provincias = [
    { id: 'distrito capital', nombre: 'Distrito Capital' },
    { id: 'amazonas', nombre: 'Amazonas' },
    { id: 'anzoategui', nombre: 'Anzoátegui' },
    { id: 'apure', nombre: 'Apure' },
    { id: 'aragua', nombre: 'Aragua' },
    { id: 'barinas', nombre: 'Barinas' },
    { id: 'bolivar', nombre: 'Bolívar' },
    { id: 'carabobo', nombre: 'Carabobo' },
    { id: 'cojedes', nombre: 'Cojedes' },
    { id: 'delta amacuro', nombre: 'Delta Amacuro' },
    { id: 'falcon', nombre: 'Falcón' },
    { id: 'guarico', nombre: 'Guárico' },
    { id: 'lara', nombre: 'Lara' },
    { id: 'merida', nombre: 'Mérida' },
    { id: 'miranda', nombre: 'Miranda' },
    { id: 'monagas', nombre: 'Monagas' },
    { id: 'nueva esparta', nombre: 'Nueva Esparta' },
    { id: 'portuguesa', nombre: 'Portuguesa' },
    { id: 'sucre', nombre: 'Sucre' },
    { id: 'tachira', nombre: 'Táchira' },
    { id: 'trujillo', nombre: 'Trujillo' },
    { id: 'vargas', nombre: 'Vargas' },
    { id: 'yaracuy', nombre: 'Yaracuy' },
    { id: 'zulia', nombre: 'Zulia' },
    { id: 'dependencias federales', nombre: 'Dependencias Federales' }
];